version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://app-db:27017/docker-node-app
    ports:
      - 8082:8082
    depends_on:
      - app-db

  app-db:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - app-db-data:/data/db

volumes:
  app-db-data:
